
-- Add comprehensive data for schools in Rouen and NEOMA Business School campuses
INSERT INTO public.school_profiles (
  name, city, slug, overview, programs, subjects, degrees, language,
  fees, living_costs, admission_requirements, language_tests, entrance_exams,
  global_rankings, recognitions, facilities, housing, student_services,
  indian_community, cultural_societies, indian_amenities,
  contact_links, detailed_programs, brochures
) VALUES 
(
  'NEOMA Business School - Rouen Campus',
  'Rouen',
  'neoma-business-school-rouen',
  'NEOMA Business School is a leading French business school with triple accreditation (AACSB, EQUIS, AMBA). The Rouen campus offers innovative programs in management and business.',
  ARRAY['Master in Management', 'MSc International Business', 'MBA', 'Bachelor in Management', 'Executive Education'],
  ARRAY['Business Management', 'International Business', 'Finance', 'Marketing', 'Strategy', 'Entrepreneurship', 'Digital Business'],
  ARRAY['Bachelor', 'Master', 'MBA', 'Executive Programs'],
  'French and English programs available',
  '€12,000-16,000 per year for Master programs, €8,000-10,000 for Bachelor',
  '€800-1,200 per month including accommodation, food, and transportation',
  'Bachelor''s degree for Master programs, High school diploma for Bachelor programs, GMAT/GRE for MBA',
  'TOEFL (90+), IELTS (6.5+), TOEIC (785+) for English programs',
  'GMAT (550+) for MBA, entrance exam for some programs',
  'Ranked among top 30 European business schools, Financial Times ranking',
  'Triple Crown accreditation (AACSB, EQUIS, AMBA), CGE member',
  'Modern campus with innovation labs, library, sports facilities, student housing',
  'On-campus residence halls, partner accommodations, housing assistance',
  'Career services, international exchange programs, entrepreneurship support',
  'Active Indian student community (50+ students), Indian Student Association',
  'Business clubs, cultural societies, international student groups',
  'Halal food options, prayer facilities, cultural celebration support',
  '{"website": "https://neoma-bs.fr", "email": "admissions@neoma-bs.fr", "phone": "+33 2 32 82 57 00", "linkedin": "https://linkedin.com/school/neoma-business-school", "instagram": "https://instagram.com/neomabs"}',
  '{"Master in Management": {"description": "2-year program with international exposure", "duration": "2 years", "specializations": ["Finance", "Marketing", "Strategy"]}, "MSc International Business": {"description": "1-year specialized master", "duration": "1 year", "specializations": ["Global Management", "Digital Business"]}}',
  '{"Master in Management": ["https://neoma-bs.fr/brochures/mim-brochure.pdf"], "MBA": ["https://neoma-bs.fr/brochures/mba-brochure.pdf"]}'
),
(
  'NEOMA Business School - Paris Campus',
  'Paris',
  'neoma-business-school-paris',
  'NEOMA Business School Paris campus is located in the heart of Paris, offering world-class business education with strong industry connections and international perspective.',
  ARRAY['Master in Management', 'MSc Programs', 'Executive MBA', 'Bachelor Programs', 'Executive Education'],
  ARRAY['Finance', 'Marketing', 'Management', 'Digital Transformation', 'Luxury Management', 'International Business'],
  ARRAY['Bachelor', 'Master', 'MBA', 'Executive Programs'],
  'French and English programs available',
  '€14,000-18,000 per year for Master programs, €10,000-12,000 for Bachelor',
  '€1,200-1,800 per month including accommodation, food, and transportation',
  'Bachelor''s degree for Master programs, Strong academic record, Professional experience for Executive programs',
  'TOEFL (90+), IELTS (6.5+), TOEIC (785+) for English-taught programs',
  'GMAT (600+) recommended for MBA, competitive entrance process',
  'Top 25 European business schools, excellent employability rankings',
  'Triple accreditation (AACSB, EQUIS, AMBA), member of Conférence des Grandes Écoles',
  'State-of-the-art facilities in Paris, innovation hubs, extensive library resources',
  'Partner accommodations, housing assistance, proximity to public transport',
  'Extensive career services, corporate partnerships, alumni network',
  'Vibrant Indian community (80+ students), regular cultural events',
  'Multiple student clubs, cultural associations, professional societies',
  'Indian food options nearby, prayer facilities, festival celebrations',
  '{"website": "https://neoma-bs.fr", "email": "paris.admissions@neoma-bs.fr", "phone": "+33 1 55 91 78 00", "linkedin": "https://linkedin.com/school/neoma-business-school", "instagram": "https://instagram.com/neomabs"}',
  '{"Master in Management": {"description": "Grande École program with luxury specialization options", "duration": "2 years", "specializations": ["Luxury Management", "Finance", "Consulting"]}, "Executive MBA": {"description": "Part-time MBA for professionals", "duration": "18 months", "specializations": ["Leadership", "Strategy", "Innovation"]}}',
  '{"Master in Management": ["https://neoma-bs.fr/brochures/mim-paris.pdf"], "Executive MBA": ["https://neoma-bs.fr/brochures/emba-brochure.pdf"]}'
),
(
  'NEOMA Business School - Reims Campus',
  'Reims',
  'neoma-business-school-reims',
  'NEOMA Business School Reims campus combines tradition with innovation, located in the historic Champagne region while offering cutting-edge business education.',
  ARRAY['Master in Management', 'Global MBA', 'MSc Programs', 'Bachelor in Management', 'Summer Programs'],
  ARRAY['Management', 'Finance', 'Marketing', 'Supply Chain', 'Data Analytics', 'Entrepreneurship'],
  ARRAY['Bachelor', 'Master', 'MBA', 'Certificate Programs'],
  'French and English programs, strong international focus',
  '€13,000-17,000 per year for Master programs, €9,000-11,000 for Bachelor',
  '€700-1,000 per month including accommodation and living expenses',
  'Strong academic background, Bachelor''s degree for Master programs, Work experience for MBA',
  'TOEFL (90+), IELTS (6.5+) for English programs, French proficiency for French programs',
  'Competitive entrance exam, GMAT recommended for MBA programs',
  'Top-ranked business school, strong international recognition',
  'AACSB, EQUIS, AMBA accreditations, member of prestigious business school networks',
  'Historic campus with modern facilities, innovation labs, extensive sports facilities',
  'On-campus housing available, support for international students',
  'Comprehensive career support, strong alumni network, internship programs',
  'Growing Indian student population (40+ students), cultural exchange programs',
  'Diverse student organizations, cultural clubs, professional associations',
  'International food options, cultural support services, festival celebrations',
  '{"website": "https://neoma-bs.fr", "email": "reims.admissions@neoma-bs.fr", "phone": "+33 3 26 77 47 47", "linkedin": "https://linkedin.com/school/neoma-business-school", "instagram": "https://instagram.com/neomabs"}',
  '{"Global MBA": {"description": "International MBA with global perspective", "duration": "12 months", "specializations": ["Global Management", "Innovation", "Sustainability"]}, "Master in Management": {"description": "Traditional Grande École program", "duration": "2 years", "specializations": ["Supply Chain", "Data Analytics", "Marketing"]}}',
  '{"Global MBA": ["https://neoma-bs.fr/brochures/global-mba.pdf"], "Master in Management": ["https://neoma-bs.fr/brochures/mim-reims.pdf"]}'
),
(
  'University of Rouen Normandy',
  'Rouen',
  'university-of-rouen-normandy',
  'University of Rouen Normandy is a comprehensive public university offering diverse academic programs across sciences, humanities, medicine, and technology with strong research focus.',
  ARRAY['Bachelor Programs', 'Master Programs', 'PhD Programs', 'Engineering Degrees', 'Medical Programs'],
  ARRAY['Computer Science', 'Engineering', 'Medicine', 'Psychology', 'Literature', 'Sciences', 'Law', 'Economics'],
  ARRAY['Bachelor (Licence)', 'Master', 'PhD (Doctorat)', 'Engineering Diploma'],
  'Primarily French, some English-taught Master programs available',
  '€170-380 per year for EU students, €2,770-3,770 for non-EU students',
  '€600-900 per month including accommodation, food, and transportation',
  'High school diploma for Bachelor, Bachelor''s degree for Master, French language proficiency',
  'DELF B2/DALF C1 for French programs, TOEFL/IELTS for English programs',
  'Competitive selection for some programs, entrance exams for specific fields',
  'Well-regarded public university, strong research rankings in specific fields',
  'Public university status, member of Normandy University alliance',
  'Multiple campuses, research laboratories, modern facilities, libraries',
  'CROUS housing, private accommodations, housing assistance available',
  'International student services, language support, career guidance',
  'International student community (25+ Indian students), cultural integration programs',
  'International student associations, cultural clubs, academic societies',
  'Diverse international community, cultural event support',
  '{"website": "https://www.univ-rouen.fr", "email": "international@univ-rouen.fr", "phone": "+33 2 35 14 60 00", "linkedin": "https://linkedin.com/school/universite-de-rouen", "instagram": "https://instagram.com/univrouen"}',
  '{"Computer Science Master": {"description": "Advanced computer science with research focus", "duration": "2 years", "specializations": ["AI", "Software Engineering", "Data Science"]}, "Engineering Programs": {"description": "Various engineering specializations", "duration": "5 years", "specializations": ["Civil", "Mechanical", "Electrical"]}}',
  '{"General Brochure": ["https://www.univ-rouen.fr/brochures/general.pdf"], "International Programs": ["https://www.univ-rouen.fr/brochures/international.pdf"]}'
),
(
  'INSA Rouen Normandy',
  'Rouen',
  'insa-rouen-normandy',
  'INSA Rouen Normandy is a prestigious engineering school part of the INSA Group, offering high-quality engineering education with strong industry connections and research excellence.',
  ARRAY['Engineering Degree', 'Master Programs', 'PhD Programs', 'International Programs', 'Continuing Education'],
  ARRAY['Civil Engineering', 'Mechanical Engineering', 'Computer Science', 'Chemical Engineering', 'Mathematics', 'Energy Systems'],
  ARRAY['Engineering Diploma (5 years)', 'Master', 'PhD'],
  'French primarily, some English-taught programs available',
  '€601 per year for EU students, €2,500 for non-EU students',
  '€700-1,000 per month including accommodation and living expenses',
  'Strong mathematics and science background, competitive entrance exam (Concours INSA)',
  'French proficiency required, TOEFL/IELTS for English programs',
  'Highly competitive entrance exam (Concours INSA), excellent academic record required',
  'Top-ranked engineering school, excellent graduate employment rates',
  'CTI accreditation, member of prestigious INSA Group and CGE',
  'Modern engineering facilities, research labs, innovation centers, student housing',
  'On-campus residences, student housing support, proximity to city center',
  'Strong career services, industry partnerships, internship programs',
  'Small but active international community (15+ Indian students)',
  'Engineering societies, cultural clubs, sports associations',
  'International student support, cultural integration assistance',
  '{"website": "https://www.insa-rouen.fr", "email": "international@insa-rouen.fr", "phone": "+33 2 32 95 97 00", "linkedin": "https://linkedin.com/school/insa-rouen", "instagram": "https://instagram.com/insarouennormandie"}',
  '{"Engineering Degree": {"description": "5-year integrated engineering program", "duration": "5 years", "specializations": ["Civil Engineering", "Mechanical Engineering", "Computer Science", "Chemical Engineering"]}, "International Master": {"description": "English-taught master programs", "duration": "2 years", "specializations": ["Advanced Engineering", "Research Track"]}}',
  '{"Engineering Programs": ["https://www.insa-rouen.fr/brochures/engineering-programs.pdf"], "International Guide": ["https://www.insa-rouen.fr/brochures/international-guide.pdf"]}'
);
